### ISSUE TITLE
system: Large file transfers from USB lead to system crash

### ISSUE THREAD

**Issue by JesseLeePalser** [linuxmint/mint22.1-beta#50] opened 2024-12-16 20:17 UTC
Clean install, not a Virtual Machine install of Linux Mint 22.1 Cinnamon Beta.
Beelink SER8 super miniPC.

Tried twice to copy over 32GB of files from a USB3 flash drive to LM 22.1 Cinnamon Beta.
About half way through both times the Operating System crashed(hard reset).

Tell me what you need to fix this and I will provide it here.
Battle testing 22.1 Beta now on a mission critical computer.

Jesse

**Comment by xeroscope-oneshot** [comment] 2024-12-16 20:20
Did you check for the latest updates?

**Comment by mtwebster** [comment] 2024-12-16 20:34
Hi please upload crash information if available:
https://projects.linuxmint.com/reference/git/bugs/mintreport-crash-info.html

**Comment by JesseLeePalser** [comment] 2024-12-17 01:11
- 22.1 Beta was fully updated.

- No crash information, Operating System was unrecoverable (hard reset)
( I looked in Start->Administration->System Reports(Crash reports) )

Is there anything else I can provide to help fix this?
I don't know anything about Linux

**Comment by xeroscope-oneshot** [comment] 2024-12-17 01:18
Could you display your hardware specs?

**Comment by JesseLeePalser** [comment] 2024-12-17 01:48
Below:
https://termbin.com/mvrp

**Comment by clefebvre** [comment] 2024-12-17 09:51
What do you mean by the "OS" crashed?

Black screen, no power? Desktop freeze, can't move the mouse? Desktop freeze, mouse still moves? Crashed back to login screen?

**Comment by clefebvre** [comment] 2024-12-17 10:22
Is this drive formatted in NTFS or exFat by any chance? I wonder if this is related to https://github.com/linuxmint/mint22.1-beta/issues/30

**Comment by Fantu** [comment] 2024-12-17 11:56
The problems could be caused by hardware problems on the usb ports, they are quite frequent and happen on both linux and windows. It is rare, however, that they cause the system to crash.
If there is a crash you should see from the kernel panic details what module is causing it in most cases.
If it is a hardware problem, it is often solved by changing the usb port, maybe even using usb2 ports instead of usb3, I have seen several cases even recently of usb3 ports that cause unexpected events (on both linux and windows) and for which I had to select usb2 ports instead (at the expense of speed)

given the amount of problems you are reporting from the same PC it is also possible that there are hardware problems with other components
for example you can check if it crashes with cpu under load or due to overheating (with benchmark and check temperature with sensors), check the ram (memtest86+) and the disk (smart data and selftest)

**Comment by spamegg1** [comment] 2024-12-26 19:00
Mini PCs aren't too well supported by the Linux kernel, they have some specialized hardware / firmware.

**Comment by clefebvre** [comment] 2024-12-27 11:39
Closing as observation.

**Closed as completed by clefebvre** 2024-12-27 11:39 UTC
Labels: observation, question
