### ISSUE TITLE
Night Light [Feature Reqest]

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/mint22.1-beta#33] opened 2024-12-13 16:43 UTC
Is is possible in the future to add the option for a user to enter their latitude and longitude for a custom location?  I noticed for Eastern Time (U.S.) New York that is gives a location of Cape Cod.  I tried to change this in dconf but after a restart it writes the Cape Cod coordinates.

Issue is, I am far from Cape Cod in the Eastern Time zone, near SW Virginia.  Sunrise and sunset will be almost 30 minutes off.  In Redshift there was the ability to enter custom coordinates in the startup desktop item.

Just asking while this feature is new/in development.

**Comment by haggen88** [comment] 2024-12-13 17:01
Hopefully in the future the night light can have that functionality (At the moment I use Qredshift which uses https://geolocation-db.com/ ).   Other useful modifications IMHO would be to reduce the preview time and to be able to specify the start/end time in more detail (currently it only allows approximations of 15minutes).

**Comment by Acheron17** [comment] 2024-12-13 17:25
The problem with entering the manual times, is that would be great if you lived on the equator.  Where I am, that time is quite variable through the year.

**Comment by zsolaj** [comment] 2024-12-14 07:18
It would also be nice if it could change the monitor brightness along with the color temperature on systems where the brightness is controllable via software (e.g. laptops). I usually lower the brightness manually as the sun sets. It would be nice if it could do it automatically. I don't think it would be too hard to implement, although, admittedly, quite a niche feature and not a very important one at that, either

**Comment by clefebvre** [comment] 2024-12-17 10:42
This should be discussed going forward. Night Light kinda mixes two different concepts which aren't exactly the same... one is to reduce contrast/eye-strain (here... sunset/sunrise are important) and one is to reduce blue-light before sleep time (here, it really doesn't matter much if it's dark outside, what matters is what time you go to bed at).

Precision is also an important design aspect. I'm not sure it matters if the sunset/bed-time is off by 10 minutes, 20 minutes, arguably even half an hour. Because the way this works is that the temperature progressively warms up hours before then.

None of it is precise really.. even the science behind it. You need less and less blue light as you get closer and closer to bed time.. but is that an exact 2 hours duration? No, and before your exact bed time? No. It's a tangible reduction for a certain amount of time.. there's no exact formula behind it afaik.

It might worth documenting exactly how this works though, just out of curiosity and for future discussions.

I'm going to close this here though since it's not a bug we can address right now in this BETA.

**Closed as completed by clefebvre** 2024-12-17 10:42 UTC
